name: Release Workflow to Deploy to Azure Kubernetes Service

on:
  release:
    types: [created, edited]
  workflow_dispatch:

permissions:
  contents: read

env:
  VERSION_TAG: ${{ github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout Code
        uses: actions/checkout@v4

      - name: 🛠️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Azure Container Registry (ACR)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DEFAULT_REGISTRY_SERVER }}
          username: ${{ secrets.DEFAULT_REGISTRY_USERNAME }}
          password: ${{ secrets.DEFAULT_REGISTRY_PASSWORD }}

      - name: 📤Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DEFAULT_REGISTRY_SERVER }}/playgroundaks:${{ env.VERSION_TAG }}
            ${{ secrets.DEFAULT_REGISTRY_SERVER }}/playgroundaks:latest
          file: ./Dockerfile
      
      - name: ☸️ Set AKS Context
        uses: Azure/aks-set-context@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}  
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}     

      - name: 🔑 Create ACR Registry Secret in Kubernetes
        uses: Azure/k8s-create-secret@v1.1
        with:
          namespace: default
          secret-type: docker-registry
          secret-name: acr_credentials
          container-registry-url: ${{ secrets.DEFAULT_REGISTRY_SERVER }}
          container-registry-username: ${{ secrets.DEFAULT_REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.DEFAULT_REGISTRY_PASSWORD }}
      
      - name: 🚀 Deploy to Kubernetes Cluster
        uses: Azure/k8s-deploy@v1
        with:
          action: deploy
          manifests: |
            k8s-specifications/demo-deployment.yaml
            k8s-specifications/demo-service.yaml
          images: |
            ${{ secrets.DEFAULT_REGISTRY_SERVER }}/playgroundaks:${{ env.VERSION_TAG }}
          imagepullsecrets: acr_credentials